version: "3.8"
name: "testcomposition"
services: 
  MyAppTestCompositionTestService1: 
    image: "redis"
    pull_policy: "always"
    restart: "always"
    expose: 
      - 9080
    ports: 
      - 19132:19132/udp
    environment: 
      BOOL: "true"
      STR: "Test"
    deploy: 
      resources: 
        limits: 
          cpus: "0.02"
    mem_reservation: "10M"
    networks: 
      MyAppTestCompositionTestNetwork1: 
      MyAppTestCompositionTestNetwork2: 
    volumes: 
      - MyAppTestCompositionTestVolume:/etc/nginx/certs
  MyAppTestCompositionTestService2: 
    image: "redis"
    pull_policy: "always"
    restart: "always"
    expose: 
      - 9080
    ports: 
      - 19132:19132/udp
    environment: 
      BOOL: "true"
      STR: "Test"
    deploy: 
      resources: 
        limits: 
          cpus: "0.02"
    mem_reservation: "10M"
    networks: 
      MyAppTestCompositionTestNetwork1: 
    depends_on: 
      - MyAppTestCompositionTestService1
networks: 
  MyAppTestCompositionTestNetwork1: 
  MyAppTestCompositionTestNetwork2: 
volumes: 
  MyAppTestCompositionTestVolume: 
