name: "composition"
services: 
  Service.HealthcheckCompositionService: 
    image: "redis"
    deploy: 
      labels: 
        de.label: label
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
