name: "composition"
services: 
  Service.CommandCompositionService: 
    image: "redis"
    environment: 
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
            brokers: ["redpanda-0:9092"]
        redpanda:
            adminApi:
                enabled: true
        urls: ["http://redpanda-0:9644"]
