version: "3.8"
name: "testcomposition"
services: 
  Composition.IntegrationCompositionTestService1: 
    image: "redis"
    pull_policy: "always"
    restart: "always"
    expose: 
      - 9080
    ports: 
      - 19132:19132/udp
    environment: 
      BOOL: true
      STR: Test
    deploy: 
      resources: 
        limits: 
          cpus: "0.02"
    mem_reservation: "10M"
    networks: 
      Composition.IntegrationCompositionTestNetwork1: 
      Composition.IntegrationCompositionTestNetwork2: 
    volumes: 
      - Composition.IntegrationCompositionTestVolume:/etc/nginx/certs
  Composition.IntegrationCompositionTestService2: 
    image: "redis"
    pull_policy: "always"
    restart: "always"
    expose: 
      - 9080
    ports: 
      - 19132:19132/udp
    environment: 
      BOOL: true
      STR: Test
    deploy: 
      resources: 
        limits: 
          cpus: "0.02"
    mem_reservation: "10M"
    networks: 
      Composition.IntegrationCompositionTestNetwork1: 
    depends_on: 
      - Composition.IntegrationCompositionTestService1
networks: 
  Composition.IntegrationCompositionTestNetwork1: 
  Composition.IntegrationCompositionTestNetwork2: 
volumes: 
  Composition.IntegrationCompositionTestVolume: 
    driver: "overlay"
